### ISSUE TITLE
always `The kernel is dead`

### ISSUE THREAD

**Issue by Edenharder** [mmatera/iwolfram#1]
jupyter --version: 4.2.0
mathematica --version: 11.0.0

I install `iwolfram` kernel with

```
pip install git+https://github.com/mmatera/iwolfram
```

**Comment by mmatera** [comment]
matlab_kernel  now suports it?

**Comment by mmatera** [comment]
By now, the kernel is in a very experimental stage. I plan to stabilize it in the next months.

**Comment by atom77** [comment]
any new updates on the kernel. I installed the kernel using "pip install -e . ",  after cloning it locally. it installed successfully. But kernel did not show up in the jupyterhub. Do I need to follow additional steps.

**Comment by mmatera** [comment]
In which operating system did you installed it? 

In an Python notebook,  check the output of

from wolfram_kernel.config import  mathexec
print(mathexec)

It should print the path of your installation of the Mathematica Kernel (for example 
/usr/local/bin/MathKernel)

**Comment by atom77** [comment]
Well, it correctly pointed out to Mathematica installation !. Seems it is working. Thanks. Do you have any examples how to use it.

**Comment by mmatera** [comment]
In that case, could you open a notebook with the kernel? In the folder "examples" you can find an ipynb with some examples.

**Comment by mmatera** [comment]
It seems that for some reason, your kernel can not recognize your version of Mathematica, and tries to use the routine for mathics. Can you check the output of
$Version

in the iwolfram kernel?

**Comment by alamgirh** [comment]
$Version
Mathics 1.1.dev0 on CPython 2.7.12 (default, Nov 19 2016, 06:48:10)  using SymPy 1.0, mpmath 0.19

**Comment by mmatera** [comment]
It seems you are using mathics as the mathematica kernel behind iwolfram. Please check that the path defined in the file config.py in the wolfram_kernel installation folder points to the  wolfram mathematica kernel executable in your system.
