### ISSUE TITLE
Can't use PlotLegends

### ISSUE THREAD

**Issue by cnkjw** [mmatera/iwolfram#9]
Firstly, thanks for author. This tool is very good! But I found some bug. When I use ```PlotLegends``` to add legends, I find it can't work.
# Example code
```mathematica
Plot[{Sin[x],Cos[x]},{x,0,10},PlotLegends -> Placed[{"Sin","Cos"},{0.2,0.2}]]
```
# Error info
> OptionValue::rep: HoldForm[None] is not a valid replacement rule.
OptionValue::rep: HoldForm[None] is not a valid replacement rule.
OptionValue::rep: HoldForm[None] is not a valid replacement rule.

When I remove ```PlotLegends```, it can work. So what should I do? Thanks!

**Comment by mmatera** [comment]
Please check the new version.
